Input color and background will now adjust with parent's styles. Styl…
Collaborne/paper-search pull request #10
Opened 2016-10-27 04:00 UTC by avdaredevil

### Things Enhanced in relation to #9 
> - Input color and background will now adjust with parent's styles.
- Styles adjusted to accommodate dynamic styles with:
  - `--icon-styles`
  - `--input-styles`
  - `--disabled-input-styles`

2016-10-27 08:21 UTC, ronnyroeller requested changes

2016-10-27 08:21 UTC, ronnyroeller commented on paper-search-bar.html
> +                @apply(--input-styles);
Can you please use tabs instead of spaces to keep the code consistent?

2016-10-27 08:21 UTC, ronnyroeller commented on paper-search-bar.html
> +                @apply(--disabled-input-styles);
Can you please use tabs instead of spaces to keep the code consistent?

2016-10-27 10:03 UTC, ankon commented
FWIW: The travis failure was caused by https://github.com/Polymer/polymer-analyzer/issues/205, I've disabled polylint checking now.

2016-10-27 18:12 UTC, avdaredevil commented on paper-search-bar.html
> +                @apply(--disabled-input-styles);
Sure thing!

2016-10-27 18:21 UTC, avdaredevil commented
Ok Tabs are fixed!

2016-11-08 17:46 UTC, avdaredevil commented
@ronnyroeller @ankon, What's holding up the pull request?

2016-11-08 23:07 UTC, merged

2016-11-08 23:07 UTC, ronnyroeller commented
Thanks for pinging, @avdaredevil . This got somehow lost.

2016-11-08 23:29 UTC, avdaredevil commented
It happens! Thanks for the component!